"""Added start date and some constraints

Revision ID: 591e82bf8419
Revises: 90ab3d81d125
Create Date: 2020-05-29 19:29:39.456093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591e82bf8419'
down_revision = '90ab3d81d125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.alter_column('account', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('level_progression', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject', 'characters',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('subject', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('subject', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject', 'characters',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('level_progression', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('account', 'start_date')
    # ### end Alembic commands ###
