"""made FKs not nullable

Revision ID: 90ab3d81d125
Revises: 4ea6a3a43d2a
Create Date: 2020-05-25 18:01:15.472618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ab3d81d125'
down_revision = '4ea6a3a43d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'username',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('assignment', 'srs_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignment', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('level_progression', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'ending_srs_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'starting_srs_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'starting_srs_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'ending_srs_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('level_progression', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignment', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignment', 'srs_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'username',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
